POST https://election-apim.azure-api.net/votes HTTP/1.1
Host: election-apim.azure-api.net
Content-Type: application/json
Ocp-Apim-Subscription-Key: 79377818374f4c578f11b9feedf4a805
Ocp-Apim-Trace: true

{"numberCandidate":0}