POST https://election-api.azure-api.net/api/candidates HTTP/1.1
Host: election-api.azure-api.net
Content-Type: application/json
Ocp-Apim-Subscription-Key: 77059e0713fa4c1c8bb399e1a6d42e3f
Ocp-Apim-Trace: true

{"name":"string","number":0,"birthDate":"string"}